package io.vepo.bookstore.stockservice;

import java.util.List;

/**
 * A {@link PreOrder} is generated by Stock. It refers a cartId that exists on the Cart
 * Services.
 * 
 * @author Victor Osório <victor.perticarrari@gmail.com>
 *
 */
public record PreOrder(String preOrderId, 
                       String cartId, 
                       List<PreOrderItem> orderItems) {}